spring:
  datasource:
    url: jdbc:h2:mem:test_db
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
  security:
    user:
      name: admin
      password: admin

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"