spring:
  mvc:
    log-resolved-exception: false
  datasource:
    url: jdbc:h2:mem:test_db;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
  h2:
    console:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"